/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-04-16 04:16:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.DAO.BookDAOImpl;
import com.entity.BookDtls;
import com.DB.DBConnect;
import java.util.List;
import com.user.servlet.*;
import com.entity.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1742379031479L));
    _jspx_dependants.put("/all_compound/navbar.jsp", Long.valueOf(1743565260056L));
    _jspx_dependants.put("/all_compound/footer.jsp", Long.valueOf(1741874424416L));
    _jspx_dependants.put("jar:file:/D:/Downloads/try/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ecommerce/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/all_compound/allcss.jsp", Long.valueOf(1735207496149L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("com.user.servlet");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.entity.BookDtls");
    _jspx_imports_classes.add("com.entity.User");
    _jspx_imports_classes.add("com.DAO.BookDAOImpl");
    _jspx_imports_classes.add("com.DB.DBConnect");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>\r\n");
      out.write("ebook \r\n");
      out.write("</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".{\r\n");
      out.write("	height:50vh;\r\n");
      out.write("	width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroll-container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    position: relative;\r\n");
      out.write("overflow-x: auto; /* Enables horizontal scrolling */\r\n");
      out.write("    -ms-overflow-style: none; /* Hides scrollbar in Internet Explorer and Edge */\r\n");
      out.write("    scrollbar-width: none;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write(".scroll-container::-webkit-scrollbar {\r\n");
      out.write("    display: none; \r\n");
      out.write("}\r\n");
      out.write(".ho {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    overflow-x: auto;\r\n");
      out.write("    scroll-behavior: smooth; /* Enables smooth scrolling */\r\n");
      out.write("    width: 100%; /* Adjust based on your layout */\r\n");
      out.write("   overflow-x: auto; /* Enables horizontal scrolling */\r\n");
      out.write("    -ms-overflow-style: none; /* Hides scrollbar in Internet Explorer and Edge */\r\n");
      out.write("    scrollbar-width: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroll-button {\r\n");
      out.write("    background-color: #f1f1f1;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroll-button.left {\r\n");
      out.write("    left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroll-button.right {\r\n");
      out.write("    right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-body img\r\n");
      out.write("{\r\n");
      out.write("border-radius:9px;\r\n");
      out.write("}\r\n");
      out.write(".lang\r\n");
      out.write("{\r\n");
      out.write(" display: flex;\r\n");
      out.write("    flex-wrap: nowrap; /* Prevents wrapping to keep items in a single line */\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("    overflow-x: auto; /* Enables horizontal scrolling */\r\n");
      out.write("    -ms-overflow-style: none; /* Hides scrollbar in Internet Explorer and Edge */\r\n");
      out.write("    scrollbar-width: none;\r\n");
      out.write("}\r\n");
      out.write("a\r\n");
      out.write("{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("text-color:black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#f0f1f2;\">\r\n");
      out.write("<section class=\"container-fluid\">\r\n");
      out.write("<div class=\"top\">\r\n");
      out.write("<hr>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");

User us=(User)session.getAttribute("userobj"); 


      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"all_compound/style.css\">\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\"\r\n");
      out.write("	 integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\" \r\n");
      out.write("	 crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("	\r\n");
      out.write("	 <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\"\r\n");
      out.write("	  integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\" \r\n");
      out.write("	  crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("     \r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("    <html>\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("   \r\n");
      out.write("    *  {\r\n");
      out.write("    font-family: \"Comic Sans MS\";\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("    </style>\r\n");
      out.write("    </head>\r\n");
      out.write("   \r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"row-md-4\">\r\n");
      out.write("\r\n");
      out.write(" <div class=\"header\"><h3><img src=\"book/ganesha_7443644.png\" style=\"width:40px;height:45px\">Shree Ganesh</h3></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"input-group ml-5 m-2 text-center\">\r\n");
      out.write("  <form action=\"search.jsp\" method=\"post\" style=\"width:80vw;\">\r\n");
      out.write("  <input type=\"text\" class=\"form-control \" placeholder=\"Seach here...\" name=\"ch\" aria-label=\"Username\" aria-describedby=\"basic-addon1\">\r\n");
      out.write("</form>\r\n");
      out.write("<div class=\"input-group-prepend ml-2\">\r\n");
      out.write("    <span class=\"input-group-text\" id=\"basic-addon1\">\r\n");
      out.write("        <a href=\"checkout.jsp\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping\" style=\"color:black\"></i>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("    </span>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"corner\">\r\n");
      out.write("<div class=\"row mx-5\">\r\n");
      out.write("<!-- <a href=\"checkout.jsp\"><i class=\"fa-regular fa-black fa-heart ml-5 m-1 fa-2x\" style=\"color:black\"></i></a>\r\n");
      out.write(" -->\r\n");
      out.write("   \r\n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"all_comic.jsp\">Comic</a>\r\n");
      out.write("      </li>\r\n");
      out.write("       <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link disabled\" href=\"all_horror.jsp\">Horror</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link disabled\" href=\"all_prog.jsp\">Programming</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item dropdown active\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("          Sorts\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"all_recent.jsp\">Recent</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"all_new.jsp\">New</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"all_old\">Old</a>\r\n");
      out.write("         \r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("     \r\n");
      out.write("    </ul>\r\n");
      out.write("     <div class=\"row-md-3\">\r\n");
      out.write("<form class=\"form-inline my-2 my-lg-2\">\r\n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" </form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"carouselExampleIndicators\" class=\"carousel slide container-fluid\" data-ride=\"carousel\">\r\n");
      out.write("  <ol class=\"carousel-indicators\">\r\n");
      out.write("    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\r\n");
      out.write("    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\r\n");
      out.write("  </ol>\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("    <div class=\"carousel-item active\">\r\n");
      out.write("      <img class=\"d-block w-100 h-50\" src=\"book/All.png\" alt=\"First slide\">\r\n");
      out.write("      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("    <h3 class=\"text-center\">Hello,");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userobj.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("    <p>kaise o app</p>\r\n");
      out.write("  </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img class=\"d-block w-100 h-50\" src=\"book/all2.jpg\" alt=\"Second slide\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img class=\"d-block w-100 h-50\" src=\"book/all3.png\" alt=\"Third slide\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"sr-only\">Previous</span>\r\n");
      out.write("  </a>\r\n");
      out.write("  <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"sr-only\">Next</span>\r\n");
      out.write("  </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<div class=\"scroll-container\">\r\n");
      out.write("  <button class=\"scroll-button left\" onclick=\"scrollright1()\">&#8249;</button>\r\n");
      out.write("  <div class=\"ho\" id=\"scrollable-container\">\r\n");


BookDAOImpl dao2=new BookDAOImpl(DBConnect.getconn());
List<BookDtls>list=dao2.getNewBook();
for(BookDtls b:list)
{
      out.write("\r\n");
      out.write("<a href=\"view_Books.jsp?bid=");
      out.print(b.getBook_Id());
      out.write("&stock=");
      out.print(b.getStock());
      out.write("\" style=\"text-decoration:none;color:black;\">\r\n");
      out.write("<div class=\"row-md-3 mt-2\">\r\n");
      out.write("<div class=\"card ml-2\">\r\n");
      out.write("<div class=\"card-body text-center\">\r\n");
      out.write("<img src=\"book/");
      out.print(b.getPhoto() );
      out.write("\" alt=\"book1\" style=\"width:20vh;height:30vh\" class=\"img-thumblin\">\r\n");
      out.write("<p><b>");
      out.print(b.getName() );
      out.write("</b></p>\r\n");
      out.write("<p>Author:");
      out.print(b.getAuthor() );
      out.write("</p>\r\n");
      out.write("<p>Price:");
      out.print(b.getPrice() );
      out.write("<i class=\"fa-solid fa-indian-rupee-sign\"></i></p>\r\n");
      out.write("<!--  <p>Categories:");
      out.print(b.getBookType());
      out.write("</p>-->\r\n");
      out.write("<div class=\"row-center\">\r\n");

if (us == null) {

      out.write("\r\n");
      out.write("    <a href=\"login.jsp\" class=\"btn btn-outline-success\">Add To Cart</a>\r\n");

} else {
    if (b.getStock() > 0) {

      out.write("\r\n");
      out.write("        <a href=\"cart?bid=");
      out.print(b.getBook_Id());
      out.write("&uid=");
      out.print(us.getId());
      out.write("&stock=");
      out.print(b.getStock());
      out.write("\" \r\n");
      out.write("           class=\"btn btn-outline-success\">Add To Cart</a>\r\n");

    } else {

      out.write("\r\n");
      out.write("        <button class=\"btn btn-outline-secondary\" disabled>Out of Stock</button>\r\n");

    }
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  <a href=\"signup.html \" class=\"btn btn-success btn-sm\">");
      out.print(b.getPrice());
      out.write("<i class=\"fa-solid fa-indian-rupee-sign\"></i></a>-->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("	</a>\r\n");
      out.write("	");

}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("   <button class=\"scroll-button right\" onclick=\"scrollRight1()\">&#8250;</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"text-center mt-1\">\r\n");
      out.write("<a href=\"all_recent.jsp\" class=\"btn btn-outline-danger btn-sm text-white\">View all</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<!-- --------------------------------------------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"scroll-container\">\r\n");
      out.write("  <button class=\"scroll-button left\" onclick=\"scrollright2()\">&#8249;</button>\r\n");
      out.write("  <div class=\"ho\" id=\"scrollable-container2\">\r\n");


BookDAOImpl dao3=new BookDAOImpl(DBConnect.getconn());
List<BookDtls>list2=dao2.getOld();
for(BookDtls b:list2)
{
      out.write("\r\n");
      out.write("<a href=\"view_Books.jsp?bid=");
      out.print(b.getBook_Id());
      out.write("&&stock=");
      out.print(b.getStock());
      out.write("\" style=\"text-decoration:none;color:black;\">\r\n");
      out.write("<div class=\"row-md-3 mt-2\">\r\n");
      out.write("<div class=\"card ml-2\">\r\n");
      out.write("<div class=\"card-body text-center\">\r\n");
      out.write("<img src=\"book/");
      out.print(b.getPhoto() );
      out.write("\" alt=\"book1\" style=\"width:20vh;height:30vh\" class=\"img-thumblin\">\r\n");
      out.write("<p><b>");
      out.print(b.getName() );
      out.write("</b></p>\r\n");
      out.write("<p>Author:");
      out.print(b.getAuthor() );
      out.write("</p>\r\n");
      out.write("<p>Price:");
      out.print(b.getPrice() );
      out.write("<i class=\"fa-solid fa-indian-rupee-sign\"></i></p>\r\n");
      out.write("  <p>Categories:");
      out.print(b.getStock() );
      out.write("</p>\r\n");
      out.write("<div class=\"row-center\">\r\n");

if (us == null) {

      out.write("\r\n");
      out.write("    <a href=\"login.jsp\" class=\"btn btn-outline-success\">Add To Cart</a>\r\n");

} else {
    if (b.getStock() > 0) {

      out.write("\r\n");
      out.write("        <a href=\"cart?bid=");
      out.print(b.getBook_Id());
      out.write("&uid=");
      out.print(us.getId());
      out.write("&stock=");
      out.print(b.getStock());
      out.write("\" \r\n");
      out.write("           class=\"btn btn-outline-success\">Add To Cart</a>\r\n");

    } else {

      out.write("\r\n");
      out.write("        <button class=\"btn btn-outline-secondary\" disabled>Out of Stock</button>\r\n");

    }
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  <a href=\"signup.html \" class=\"btn btn-success btn-sm\">");
      out.print(b.getPrice());
      out.write("<i class=\"fa-solid fa-indian-rupee-sign\"></i></a>-->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("	</a>\r\n");
      out.write("	");

}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("   <button class=\"scroll-button right\" onclick=\"scrollRight2()\">&#8250;</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text-center mt-1\">\r\n");
      out.write("<a href=\"all_recent.jsp\" class=\"btn btn-outline-danger btn-sm text-white\">View all</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid pt-4\">\r\n");
      out.write(" <div class=\"footer\" style=\"boarder-radius:10px\"></div>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <style>\r\n");
      out.write("  \r\n");
      out.write("    footer{\r\n");
      out.write("        background: #343434;\r\n");
      out.write("        padding-top: 50px;\r\n");
      out.write("         font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .container{\r\n");
      out.write("        width: 1140px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-content{\r\n");
      out.write("        width: 33.3%;\r\n");
      out.write("    }\r\n");
      out.write("    h3{\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-content p{\r\n");
      out.write("        width:190px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        padding: 7px;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-content ul{\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .list{\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .list li{\r\n");
      out.write("        width: auto;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        list-style-type:none;\r\n");
      out.write("        padding: 7px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .list li::before{\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        transform: translate(-50%,-50%);\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        top: 100%;\r\n");
      out.write("        width: 0;\r\n");
      out.write("        height: 2px;\r\n");
      out.write("        background: #f18930;\r\n");
      out.write("        transition-duration: .5s;\r\n");
      out.write("    }\r\n");
      out.write("    .list li:hover::before{\r\n");
      out.write("        width: 70px;\r\n");
      out.write("    }\r\n");
      out.write("    .social-icons{\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .social-icons li{\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .social-icons i{\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("    }\r\n");
      out.write("    a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    a:hover{\r\n");
      out.write("        color: #f18930;\r\n");
      out.write("    }\r\n");
      out.write("    .social-icons i:hover{\r\n");
      out.write("        color: #f18930;\r\n");
      out.write("    }\r\n");
      out.write("    .bottom-bar{\r\n");
      out.write("        background: #f18930;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("        margin-top: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .bottom-bar p{\r\n");
      out.write("        color: #343434;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        padding: 7px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <h3>Contact Us</h3>\r\n");
      out.write("                <p>Email:Info@example.com</p>\r\n");
      out.write("                <p>Phone:+91 8879482456</p>\r\n");
      out.write("                <p>Address: Upper Govind Nagar, Goregoan(E)</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <h3>Quick Links</h3>\r\n");
      out.write("                 <ul class=\"list\">\r\n");
      out.write("                    <li><a href=\"../index.jsp\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"../index.jsp\">About</a></li>\r\n");
      out.write("                    <li><a href=\"../index.jsp\">Services</a></li>\r\n");
      out.write("                    <li><a href=\"../index.jsp\">Products</a></li>\r\n");
      out.write("                    <li><a href=\"../index.jsp\">Contact</a></li>\r\n");
      out.write("                 </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <h3>Follow Us</h3>\r\n");
      out.write("                <ul class=\"social-icons\">\r\n");
      out.write("                 <li><a href=\"\"><i class=\"fab fa-facebook\"></i></a></li>\r\n");
      out.write("                 <li><a href=\"\"><i class=\"fab fa-twitter\"></i></a></li>\r\n");
      out.write("                 <li><a href=\"\"><i class=\"fab fa-instagram\"></i></a></li>\r\n");
      out.write("                 <li><a href=\"\"><i class=\"fab fa-linkedin\"></i></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bottom-bar\">\r\n");
      out.write("            <p>&copy; 2023 your company . All rights reserved</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("        function scrollContainer(distance) {\r\n");
      out.write("            const container = document.querySelector('.book-container');\r\n");
      out.write("            container.scrollBy({\r\n");
      out.write("                left: distance,\r\n");
      out.write("                behavior: 'smooth'\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function changeQuantity(button, change) {\r\n");
      out.write("            const input = button.parentElement.querySelector('input');\r\n");
      out.write("            let currentValue = parseInt(input.value);\r\n");
      out.write("            currentValue += change;\r\n");
      out.write("            if (currentValue < 1) currentValue = 1;\r\n");
      out.write("            input.value = currentValue;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function scrollright1() {\r\n");
      out.write("        	\r\n");
      out.write("            const container = document.getElementById('scrollable-container');\r\n");
      out.write("            container.scrollLeft -= 100; // Adjust the value as needed\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function scrollRight1() {\r\n");
      out.write("            const container = document.getElementById('scrollable-container');\r\n");
      out.write("            container.scrollLeft += 100; // Adjust the value as needed\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("  function scrollright2() {\r\n");
      out.write("        	\r\n");
      out.write("            const container = document.getElementById('scrollable-container2');\r\n");
      out.write("            container.scrollLeft -= 100; // Adjust the value as needed\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function scrollRight2() {\r\n");
      out.write("            const container = document.getElementById('scrollable-container2');\r\n");
      out.write("            container.scrollLeft += 100; // Adjust the value as needed\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /all_compound/navbar.jsp(36,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.cart}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                <span class=\"badge badge-danger\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.cart.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /all_compound/navbar.jsp(50,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userobj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("   <!-- User Present -->\r\n");
        out.write(" <div class=\"col-md-my-2\">\r\n");
        out.write("<!-- <a href=\"login.jsp \" class=\"btn btn-light\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userobj.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</a> \r\n");
        out.write("<a href=\"logout\" class=\"btn btn-light\">LogOut</a>-->\r\n");
        out.write("</div>\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /all_compound/navbar.jsp(57,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userobj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<div class=\"col-md-my-2\">\r\n");
        out.write("<!--<a href=\"login.jsp \" class=\"btn btn-outline-secondary\">Login</a>\r\n");
        out.write("   <a href=\" signup.html\"><i class=\"fa-regular fa-user fa-2x\"></i></a> -->                                \r\n");
        out.write("\r\n");
        out.write("</div>\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /all_compound/navbar.jsp(109,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userobj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("  <!-- User Present -->\r\n");
        out.write("   <div class=\"col-md-my-2\">\r\n");
        out.write("<a href=\"setting.jsp\" class=\"btn btn-outline-secondary\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userobj.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("<i class=\"fa-regular fa-circle-user\"></i></a>\r\n");
        out.write("<!--<a href=\"setting.jsp\" class=\"btn btn-outline-secondary\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userobj.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</a>\r\n");
        out.write("  <a href=\"logout\" class=\"btn btn-light\">LogOut</a>-->\r\n");
        out.write("</div>\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /all_compound/navbar.jsp(117,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userobj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write(" <div class=\"col-md-my-2\">\r\n");
        out.write("<a href=\"setting.jsp \" class=\"btn btn-outline-secondary\">Login</a>\r\n");
        out.write("<!--  <a href=\"logout\" class=\"btn btn-light\">LogOut</a>-->\r\n");
        out.write("</div>\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }
}
